add_library(Reflect STATIC
	${LIB_SOURCE_FILES}
	${LIB_HEADER_FILES}
)

target_include_directories(Reflect
    PUBLIC
		$<INSTALL_INTERFACE:include>
		$<BUILD_INTERFACE:${LIB_INCLUDE_DIR}>
	PRIVATE
        ${LIB_INCLUDE_DIR}
)

install(TARGETS Reflect
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}/$<CONFIG>
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}/$<CONFIG>
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}/$<CONFIG>
    PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)
install(DIRECTORY "${LIB_INCLUDE_DIR}/"
        DESTINATION "include"
        FILES_MATCHING
        PATTERN "*.*"
)